### ISSUE TITLE
Could you explain in detail how to use conda virtual environment?

### ISSUE THREAD

**Issue by Mostrem** [bonbon-rj/InstructDriver#1]
nuplan, LLaMA2-Accessory，instruct_driver. I don't how to use them in various situations.

**Comment by bonbon-rj** [comment]
First, you'll need to create and activate a conda virtual environment. 
Next, within this environment, set up the necessary settings to run LLaMA2-Accessory by following the guidelines provided in the official doc. 
Following that, in the same environment, configure the environment for running nuplan-devkit, as detailed in the official doc.
Finally, in the same environment, clone our repository and run it.

**Comment by Mostrem** [comment]
Thank you. I have resolved it.
