### ISSUE TITLE
About Inference Efficiency

### ISSUE THREAD

**Issue by memberRE** [bonbon-rj/InstructDriver#2]
Hello,

I'd like to commend your outstanding work. I have a question regarding the time it took to complete the full tests (Test14-random, Test14-hard) mentioned in your paper. As far as I understand, following nuplan's inference frequency, a scenario requires 150 full LLM inferences, which seems to be an extremely time-consuming process.

I am also conducting research in this area and have recently been exploring related topics. Additionally, I have found that having the LLM directly output waypoints makes it very difficult to fit the road centerline, especially in curved lanes.

Could I have your email address for further contact?

Thank you!

**Comment by bonbon-rj** [comment]
Thank you for your recognition. Conducting a complete test is indeed a time-consuming process. Depending on the length of the output, it can take 1 to 3 days. Please feel free to reach out to me at 929096570@qq.com. Looking forward to your email!
